
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 05 23:43:23 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 40;
  public static final int CONST = 3;
  public static final int CASE = 26;
  public static final int LPAREN = 14;
  public static final int SEMI = 25;
  public static final int CONTINUE = 27;
  public static final int NUM_CONST = 39;
  public static final int MINUS = 21;
  public static final int RPAREN = 15;
  public static final int COMMA = 10;
  public static final int CLASS = 35;
  public static final int INC = 16;
  public static final int DIV = 23;
  public static final int PLUS = 20;
  public static final int IF = 30;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int LSQRTBRACE = 11;
  public static final int EQUAL = 13;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int MOD = 24;
  public static final int IDENT = 38;
  public static final int BREAK = 36;
  public static final int VOID = 4;
  public static final int SWITCH = 31;
  public static final int COLON = 18;
  public static final int LBRACE = 8;
  public static final int ELSE = 29;
  public static final int ENUM = 34;
  public static final int READ = 5;
  public static final int WHILE = 32;
  public static final int RSQRTBRACE = 12;
  public static final int RBRACE = 9;
  public static final int EXTENDS = 28;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 41;
  public static final int QUESTION = 19;
  public static final int DEC = 17;
  public static final int PRINT = 6;
  public static final int DO = 33;
}

