
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  /*public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;*/
	
	
	//keywords
	
	public static final int PROG = 1;
	public static final int BREAK = 2;
	public static final int CLASS = 3;
	public static final int ENUM = 4;
	public static final int ELSE = 5;
	public static final int CONST = 6;
	public static final int IF = 7;
	public static final int SWITCH = 8;
	public static final int DO = 9;
	public static final int WHILE = 10;
	public static final int NEW = 11;
	public static final int PRINT = 12;
	public static final int READ = 13;
	public static final int RETURN = 14;
	public static final int VOID = 15;
	public static final int EXTENDS = 16;
	public static final int CONTINUE = 17;
	public static final int CASE = 18;
	public static final int INT = 42;
	public static final int CHAR = 43;
	public static final int BOOL = 44;
	
			
	
	
	
	//identifiers
	public static final int IDENT = 19;
	
	
	//constants
	public static final int NUM_CONST = 20;
	public static final int CHAR_CONST = 21;
	public static final int BOOL_CONST = 22;
	
	
	
	//operators
	public static final int PLUS = 23;
	public static final int MINUS = 24;
	public static final int MUL = 25;
	public static final int DIV = 26;
	public static final int MOD = 27;
	public static final int EQUAL = 28;
	public static final int INC = 29;
	public static final int DEC = 30;
	public static final int SEMI = 31;
	public static final int COMMA = 32;
	public static final int LPAREN = 33;
	public static final int RPAREN = 34;
	public static final int LSQRTBRACE = 35;
	public static final int RSQRTBRACE = 36;
	public static final int LBRACE = 37;
	public static final int RBRACE = 38;
	public static final int QUESTION = 39;
	public static final int COLON = 40;
	
	
	public static final int EOF = 41;
	
	
}

